name: fltrdfctscn
description: "Defect scanner for Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^13.0.0
  mobile_scanner: ^4.0.0
  http: ^1.2.0
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  flutter_svg: ^2.0.7
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1  
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  webview_flutter: ^4.7.0
  lottie: ^3.1.2
  clay_containers: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.8.0
  test: ^1.24.0
  mocktail: ^1.0.3
  riverpod_test: ^0.1.4

flutter:
  uses-material-design: true
  assets: 
    - assets/lottie/ok.json
    - assets/icons/defects/
    - assets/icons/defects/defect_bad_top.png
    - assets/icons/defects/defect_bad_bottom.png
    - assets/icons/defects/defect_bad_set.png
    - assets/icons/defects/defect_size_top.png
    - assets/icons/defects/defect_size_bottom.png
    - assets/icons/defects/defect_size_set.png
    - assets/icons/defects/defect_color.png
    - assets/icons/defects/defect_other.png
    - assets/icons/defects/defect_ok.png